@baseUrl = http://localhost:5000
@productoId = 36dacdba-4416-4046-b373-6adce71478b9

### Crear producto de menu
POST {{baseUrl}}/api/productos
Content-Type: application/json
Accept: application/json

{
  "nombre": "Milanesa napolitanass",
  "precio": 25.50
}

### Obtener producto por id
GET {{baseUrl}}/api/productos/{{productoId}}
Accept: application/json
