@baseUrl = http://localhost:5000
@ventaId = 53352250-2322-4901-b463-228e30ea24ce
@productoId = d69c784f-423b-499e-9c71-de0f623cca8d
@detalleId = abcf6a03-3665-4330-9218-e670a0eaa6f2

### Crear venta
POST {{baseUrl}}/api/ventas
Content-Type: application/json
Accept: application/json

{
  "clienteId": "00000000-0000-0000-0000-000000000099",
  "numeroMesa": 7
}

### Obtener venta por id
GET {{baseUrl}}/api/ventas/{{ventaId}}
Accept: application/json

### Agregar producto a venta
POST {{baseUrl}}/api/ventas/{{ventaId}}/detalles
Content-Type: application/json
Accept: application/json

{
  "productoMenuId": "{{productoId}}",
  "cantidad": 2
}

### Cambiar cantidad de detalle
PUT {{baseUrl}}/api/ventas/{{ventaId}}/detalles/{{detalleId}}
Content-Type: application/json
Accept: application/json

{
  "nuevaCantidad": 3
}

### Eliminar detalle de venta
DELETE {{baseUrl}}/api/ventas/{{ventaId}}/detalles/{{detalleId}}
Accept: application/json

### Pagar venta
POST {{baseUrl}}/api/ventas/{{ventaId}}/pagar
Content-Type: application/json
Accept: application/json

{
  "metodoPago": "Tarjeta"
}

### Cancelar venta
POST {{baseUrl}}/api/ventas/{{ventaId}}/cancelar
Accept: application/json
