// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestauranteVentas.Infrastructure.Persistencia;

#nullable disable

namespace RestauranteVentas.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(RestauranteVentasDbContext))]
    [Migration("20260728081425_ProcesamientoSeguroOutbox")]
    partial class ProcesamientoSeguroOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestauranteVentas.Dominio.Productos.ProductoMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_monto");

                    b.HasKey("Id");

                    b.HasIndex("EstaActivo", "Nombre")
                        .HasDatabaseName("IX_productos_menu_activo_nombre");

                    b.ToTable("productos_menu", null, t =>
                        {
                            t.HasCheckConstraint("CK_productos_menu_nombre_no_vacio", "length(btrim(\"nombre\")) > 0");

                            t.HasCheckConstraint("CK_productos_menu_precio_positivo", "\"precio_monto\" > 0");
                        });
                });

            modelBuilder.Entity("RestauranteVentas.Dominio.Ventas.DetalleVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("NombreHistorico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_historico");

                    b.Property<decimal>("PrecioUnitarioHistorico")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_unitario_monto");

                    b.Property<Guid>("ProductoMenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_menu_id");

                    b.Property<Guid>("venta_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductoMenuId");

                    b.HasIndex("venta_id");

                    b.ToTable("detalles_venta", null, t =>
                        {
                            t.HasCheckConstraint("CK_detalles_venta_cantidad_positiva", "\"cantidad\" > 0");

                            t.HasCheckConstraint("CK_detalles_venta_nombre_historico_no_vacio", "length(btrim(\"nombre_historico\")) > 0");

                            t.HasCheckConstraint("CK_detalles_venta_precio_unitario_positivo", "\"precio_unitario_monto\" > 0");
                        });
                });

            modelBuilder.Entity("RestauranteVentas.Dominio.Ventas.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCancelacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cancelacion_utc");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTime?>("FechaPagoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago_utc");

                    b.Property<int?>("Mesa")
                        .HasColumnType("integer")
                        .HasColumnName("numero_mesa");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("metodo_pago");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelacion");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "FechaCreacionUtc")
                        .HasDatabaseName("IX_ventas_estado_fecha_creacion_utc");

                    b.ToTable("ventas", null, t =>
                        {
                            t.HasCheckConstraint("CK_ventas_cliente_id_no_vacio", "\"cliente_id\" IS NULL OR \"cliente_id\" <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("CK_ventas_estado_valido", "\"estado\" IN ('Abierta', 'Pagada', 'Cancelada')");

                            t.HasCheckConstraint("CK_ventas_fecha_cancelacion_posterior", "\"fecha_cancelacion_utc\" IS NULL OR \"fecha_cancelacion_utc\" > \"fecha_creacion_utc\"");

                            t.HasCheckConstraint("CK_ventas_fecha_creacion_valida", "\"fecha_creacion_utc\" > TIMESTAMPTZ '0001-01-01 00:00:00+00'");

                            t.HasCheckConstraint("CK_ventas_fecha_pago_posterior", "\"fecha_pago_utc\" IS NULL OR \"fecha_pago_utc\" > \"fecha_creacion_utc\"");

                            t.HasCheckConstraint("CK_ventas_metodo_pago_valido", "\"metodo_pago\" IS NULL OR \"metodo_pago\" IN ('Efectivo', 'Tarjeta', 'Transferencia')");

                            t.HasCheckConstraint("CK_ventas_numero_mesa_positivo", "\"numero_mesa\" IS NULL OR \"numero_mesa\" > 0");

                            t.HasCheckConstraint("CK_ventas_transicion_estado_coherente", "(\"estado\" = 'Abierta' AND \"fecha_pago_utc\" IS NULL AND \"metodo_pago\" IS NULL AND \"fecha_cancelacion_utc\" IS NULL AND \"motivo_cancelacion\" IS NULL) OR (\"estado\" = 'Pagada' AND \"fecha_pago_utc\" IS NOT NULL AND \"metodo_pago\" IS NOT NULL AND \"fecha_cancelacion_utc\" IS NULL AND \"motivo_cancelacion\" IS NULL) OR (\"estado\" = 'Cancelada' AND \"fecha_pago_utc\" IS NULL AND \"metodo_pago\" IS NULL AND \"fecha_cancelacion_utc\" IS NOT NULL AND length(btrim(coalesce(\"motivo_cancelacion\", ''))) > 0)");
                        });
                });

            modelBuilder.Entity("RestauranteVentas.Infrastructure.Persistencia.Outbox.OutboxMensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BloqueadoHastaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_hasta_utc");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en_utc");

                    b.Property<string>("ErrorProcesamiento")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_procesamiento");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<DateTime>("OcurridoEnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en_utc");

                    b.Property<DateTime?>("ProcesadoEnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en_utc");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tipo_evento");

                    b.Property<Guid?>("TokenBloqueo")
                        .HasColumnType("uuid")
                        .HasColumnName("token_bloqueo");

                    b.HasKey("Id");

                    b.HasIndex("ProcesadoEnUtc", "BloqueadoHastaUtc", "OcurridoEnUtc")
                        .HasDatabaseName("IX_outbox_mensajes_pendientes_ocurrido");

                    b.ToTable("outbox_mensajes", null, t =>
                        {
                            t.HasCheckConstraint("CK_outbox_mensajes_intentos_no_negativos", "\"intentos\" >= 0");
                        });
                });

            modelBuilder.Entity("RestauranteVentas.Dominio.Ventas.DetalleVenta", b =>
                {
                    b.HasOne("RestauranteVentas.Dominio.Ventas.Venta", null)
                        .WithMany("Detalles")
                        .HasForeignKey("venta_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestauranteVentas.Dominio.Ventas.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
