// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestauranteVentas.Infrastructure.Persistencia;

#nullable disable

namespace RestauranteVentas.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(RestauranteVentasDbContext))]
    [Migration("20260721174624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestauranteVentas.Dominio.Productos.ProductoMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_monto");

                    b.HasKey("Id");

                    b.ToTable("productos_menu", (string)null);
                });

            modelBuilder.Entity("RestauranteVentas.Dominio.Ventas.DetalleVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("NombreHistorico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_historico");

                    b.Property<decimal>("PrecioUnitarioHistorico")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_unitario_monto");

                    b.Property<Guid>("ProductoMenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_menu_id");

                    b.Property<Guid>("venta_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductoMenuId");

                    b.HasIndex("venta_id");

                    b.ToTable("detalles_venta", (string)null);
                });

            modelBuilder.Entity("RestauranteVentas.Dominio.Ventas.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTime?>("FechaPagoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago_utc");

                    b.Property<int?>("Mesa")
                        .HasColumnType("integer")
                        .HasColumnName("numero_mesa");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("metodo_pago");

                    b.HasKey("Id");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("RestauranteVentas.Dominio.Ventas.DetalleVenta", b =>
                {
                    b.HasOne("RestauranteVentas.Dominio.Ventas.Venta", null)
                        .WithMany("Detalles")
                        .HasForeignKey("venta_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestauranteVentas.Dominio.Ventas.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
